language: node_js
node_js:
  - node
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: $AWS_BUCKET
  skip_cleanup: true
  local_dir: lib/apps/main.ui/build
  script:
    - yarn install
    - yarn build
